name: PixelmonStrengthen
main: top.mrxiaom.pixelmonstrengthen.Main
version: 1.0.2
author: Mr_Xiao_M
softdepends: ["Vault", "PlayerPoints"]
commands:
   pixelmonstrengthen:
      usage: /pixelmonstrengthen help
   ps:
      usage: /ps help